### ISSUE TITLE
missing key or value for Dataset.Domain error occurs.

### ISSUE THREAD

**Issue by gorogoroyasu** [awslabs/improving-forecast-accuracy-with-machine-learning#2]
Thanks for this nice project.
By using this project, I think I would be able to forecast the future, and I'm really excited!

By the way, when I was trying to use this software, I met an error and I couldn't solve it.
I describe how I got the error below.

I created my Environment through the link in [this page](https://aws.amazon.com/jp/solutions/implementations/improving-forecast-accuracy-with-machine-learning/).

I uploaded `forecast-defaults.yaml` which was located at [source/example/1-defaults](https://github.com/awslabs/improving-forecast-accuracy-with-machine-learning/tree/master/source/example/1-defaults) in this project to s3 bucket which starts from `forecast-stack-data-bucket-`.

After that, I created `train` folder, and uploaded `ts.csv` and `ts.metadata.csv` which was created by following this [README.md](https://github.com/awslabs/improving-forecast-accuracy-with-machine-learning/tree/master/source/synthetic).
The command I generated ts.csv, and ts.metadata.csv was `./create_synthetic_data.py --start 2000-01-01 --length 105120`.

Then, step function started automatically, though `Create-DatasetGroup` Lambda function raise an error shown below.

```
"statesError": {
    "Error": "ValueError",
    "Cause": "{\"errorMessage\": \"configuration item missing key or value for Dataset.Domain\", \"errorType\": \"ValueError\", \"stackTrace\": [\"  File \\\"/var/task/shared/helpers.py\\\", line 62, in wrapper\\n    (status, output) = f(event, context)\\n\", \"  File \\\"/var/task/handler.py\\\", line 30, in createdatasetgroup\\n    dataset_groups = config.dataset_groups(dataset_file)\\n\", \"  File \\\"/var/task/shared/config.py\\\", line 249, in dataset_groups\\n    ds = self.dataset(dataset_file)\\n\", \"  File \\\"/var/task/shared/config.py\\\", line 149, in dataset\\n    \\\"dataset_domain\\\": self.dataset_domain(dataset_file),\\n\", \"  File \\\"/var/task/shared/config.py\\\", line 98, in dataset_domain\\n    domain = self.config_item(dataset_file, \\\"Dataset.Domain\\\")\\n\", \"  File \\\"/var/task/shared/config.py\\\", line 88, in config_item\\n    raise ValueError(f\\\"configuration item missing key or value for {item}\\\")\\n\"]}"
  }
```

Actually I don't know if it is a bug or some configuration issue... 
Anyways, I couldn't find any document about this error, and I had no ideas to fix it. 
If you know how to fix it, please let me know.

Thanks.

**Comment by pwrmiller** [comment]
Hi @gorogoroyasu - I'm glad to see you're interested in the solution! 

Using the default configuration file for the synthetic data tool, you will end up with two `.csv` files, `ts.csv` and `ts.metadata.csv`. They follow a specific schema, which must be defined in your `forecast-defaults.yaml` file. The defaults section in the configuration file you uploaded from `example/1-defaults` does not contain a configuration that is can consume the two generated files. In fact, the error you're seeing is because your configuration file does not have a declared dataset domain for the metadata file you've provided. 

To fix - replace that `forecast-defaults.yaml` file with this data: 

```
Default:
  DatasetGroup:
    Domain: RETAIL

  Datasets:
    - Domain: RETAIL
      DatasetType: TARGET_TIME_SERIES
      DataFrequency: 15min
      TimestampFormat: yyyy-MM-dd HH:mm:ss
      Schema:
        Attributes:
          - AttributeName: item_id
            AttributeType: string
          - AttributeName: timestamp
            AttributeType: timestamp
          - AttributeName: demand
            AttributeType: float
          - AttributeName: location
            AttributeType: string

    - Domain: RETAIL
      DatasetType: ITEM_METADATA
      Schema:
        Attributes:
          - AttributeName: item_id
            AttributeType: string
          - AttributeName: brand
            AttributeType: string

  Predictor:
    AlgorithmArn: arn:aws:forecast:::algorithm/Prophet
    MaxAge: 604800  # one week
    ForecastHorizon: 60
    FeaturizationConfig:
      ForecastFrequency: D
      ForecastDimensions: ["location"]

  Forecast:
    ForecastTypes:
      - "0.10"
      - "0.50"
      - "0.90"
```

Before you do this, make sure you clean up all of the generated resources in the Forecast console, or you'll have a mismatching configuration with the configuration file, so delete, under the 'ts' dataset group:

- any generated dataset groups 
- any generated datasets
- any generated dataset import jobs 

Once you've cleaned that up, upload the `forecast-defaults.yaml` file that I showed above, then upload your time series data again to S3. The forecast should proceed.

**Comment by gorogoroyasu** [comment]
Thanks for your early reply! (And I'm sorry for my late reply)

I fixed the `forecast-defaults.yaml` and tried the flow again.
The step function turned to all green! 

But, I had an problem. metadata dataset was not created.
I will try again with some conditions, though I write here what I did.
If you have some suggestions, please tell me...

1. I uploaded `forecast-default.yaml` to the bucket root.
2. I uploaded `ts.csv` and `ts.metadata.csv` to  the train folder. I uploaded them at the same time, but may be uploading metadata csv will finish earlier.

I suspect that the order of uploading file affects it. Am I correct?

Your early and accurate reply helped me a lot!  Thanks Again!!

**Comment by pwrmiller** [comment]
No problem. I'm not sure what you mean yb "metadata dataset was not created" in this context - if you uploaded both ts and ts.metadata.csv to the S3 'train' folder, you should see two things: 

1. The step function should start twice (once for the ts.metadata.csv and once for the ts.csv) 
2. In Amazon Forecast, you will see one dataset group created (ts) 
3. In Amazon Forecast, you should see two datasets under the dataset group ts, called ts and ts_metadata 
4. In the step function, both runs should succeed (though one will stop before generating the predictor). 

After some time, the forecast should be generated. The ordering of the artifact upload should not matter (the last to arrive should be the one that triggers the predictor generation - you can see which one was the most recent by looking at the tags on your dataset group). 

Can you clarify what you think is missing?

**Comment by gorogoroyasu** [comment]
I will describe what is happening with some screenshots.

This is my S3 bucket screenshot.
![S3_bucket_en](https://user-images.githubusercontent.com/17561419/106228619-1e85c400-622f-11eb-9dcc-dfbfecd8856e.png)



`forecast-defaults.yaml` I am using is what you mentioned above.

next, the result of step function.
![step_function_graph_inspector_en](https://user-images.githubusercontent.com/17561419/106228578-0150f580-622f-11eb-80de-b04816c6ae26.png)



And the last, forecast datasets which is related to my `ts` project.

![forecast_datasets](https://user-images.githubusercontent.com/17561419/106228424-ac14e400-622e-11eb-906d-1002633f77a2.png)

I think this forecast project is not using metadata dataset.

If you need more information, please let me know!
thank you.

**Comment by pwrmiller** [comment]
I see what's going on here: the `Default` key makes the implicit assumption that you have no `ITEM_METADATA` and `RELATED_TIME_SERIES` data. As such, try using this `forecast-defaults.yaml` file and retry. This is alluded to in the documentation but not specifically called out. I'll update the documentation in a future release! 

```yaml
ts:  # to allow metadata and related time series data, you must use an override
  DatasetGroup:
    Domain: RETAIL

  Datasets:
    - Domain: RETAIL
      DatasetType: TARGET_TIME_SERIES
      DataFrequency: 15min
      TimestampFormat: yyyy-MM-dd HH:mm:ss
      Schema:
        Attributes:
          - AttributeName: item_id
            AttributeType: string
          - AttributeName: timestamp
            AttributeType: timestamp
          - AttributeName: demand
            AttributeType: float
          - AttributeName: location
            AttributeType: string

    - Domain: RETAIL
      DatasetType: ITEM_METADATA
      Schema:
        Attributes:
          - AttributeName: item_id
            AttributeType: string
          - AttributeName: brand
            AttributeType: string

  Predictor:
    AlgorithmArn: arn:aws:forecast:::algorithm/Prophet
    MaxAge: 604800  # one week
    ForecastHorizon: 60
    FeaturizationConfig:
      ForecastFrequency: D
      ForecastDimensions: ["location"]

  Forecast:
    ForecastTypes:
      - "0.10"
      - "0.50"
      - "0.90"
 
Default:  # the default key must be present 
  DatasetGroup:
    Domain: RETAIL

  Datasets:
    - Domain: RETAIL
      DatasetType: TARGET_TIME_SERIES
      DataFrequency: D
      TimestampFormat: yyyy-MM-dd
      Schema:
        Attributes:
          - AttributeName: item_id
            AttributeType: string
          - AttributeName: timestamp
            AttributeType: timestamp
          - AttributeName: demand
            AttributeType: float

  Predictor:
    MaxAge: 604800  # one week
    PerformAutoML: True
    ForecastHorizon: 30
    FeaturizationConfig:
      ForecastFrequency: D

  Forecast:
    ForecastTypes:
      - "0.01"
      - "0.50"
      - "0.99"
```

The solution makes this assumption to make it easier for novice users to copy files in and get a forecast out for each file (most users don't have item metadata, for instance).
